/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSApplication.h"

@interface NSApplication (SEAppScripting)
- (id)languages;
- (id)selection;
- (void)setSelection:(id)fp8;
- (id)valueInLanguagesAtIndex:(unsigned int)fp8;
- (id)valueInLanguagesWithName:(id)fp8;
- (id)valueInLanguagesWithUniqueID:(id)fp8;
@end

