/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@interface SEAppDelegate : NSObject
{
    BOOL _navigationBarVisible;
}

- (BOOL)navigationBarVisible;
- (void)setNavigationBarVisible:(BOOL)fp8;
- (void)handleOpenLocationAppleEvent:(id)fp8 withReplyEvent:(id)fp12;
- (void)registerEventHandlers;
- (void)applicationWillFinishLaunching:(id)fp8;
- (void)applicationDidFinishLaunching:(id)fp8;
- (void)applicationWillTerminate:(id)fp8;
- (BOOL)application:(id)fp8 openFile:(id)fp12;
- (void)orderFrontAboutPanel:(id)fp8;
- (void)showPreferences:(id)fp8;
- (void)showResultHistory:(id)fp8;
- (void)showEventLogHistory:(id)fp8;
- (void)saveAsDefaultWindow:(id)fp8;
- (void)toggleNavigationBarShown:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (void)makeNewAppleScript:(id)fp8 userData:(id)fp12 error:(id *)fp16;
- (void)runAsAppleScript:(id)fp8 userData:(id)fp12 error:(id *)fp16;

@end

