/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDrawer, NSMenu, NSSegmentedControl, NSView, SEDocument, SEOutlineView;

@interface SEBundleContentsController : NSObject
{
    SEDocument *_document;
    NSDrawer *_drawer;
    NSView *_view;
    SEOutlineView *_outlineView;
    NSMenu *_actionMenu;
    NSSegmentedControl *_actionButton;
}

- (void)dealloc;
- (void)awakeFromNib;
- (id)document;
- (void)setDocument:(id)fp8;
- (id)drawer;
- (void)setDrawer:(id)fp8;
- (id)view;
- (void)setView:(id)fp8;
- (id)outlineView;
- (void)setOutlineView:(id)fp8;
- (id)actionMenu;
- (void)setActionMenu:(id)fp8;
- (id)actionButton;
- (void)setActionButton:(id)fp8;
- (BOOL)drawerVisible;
- (void)toggleBundleContents:(id)fp8;
- (void)newFolder:(id)fp8;
- (void)deleteItems:(id)fp8;
- (void)duplicateItems:(id)fp8;
- (void)openItems:(id)fp8;
- (void)revealItems:(id)fp8;
- (void)renameItem:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (id)_pathsOfSelectedItems;
- (id)_pathForItem:(id)fp8;
- (id)_pathForItem:(id)fp8 isFolder:(char *)fp12;

@end

