/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class SEDataRow;

@interface SEDataCell : NSObject
{
    SEDataRow *_dataRow;
    id _name;
    id _objectValue;
}

+ (id)cellForRow:(id)fp8 withName:(id)fp12 andValue:(id)fp16;
- (id)initForRow:(id)fp8 withName:(id)fp12 andValue:(id)fp16;
- (id)init;
- (void)dealloc;
- (id)dataRow;
- (void)setDataRow:(id)fp8;
- (id)dataItem;
- (void)setDataItem:(id)fp8;
- (id)name;
- (void)setName:(id)fp8;
- (id)content;
- (void)setContent:(id)fp8;
- (id)objectValue;
- (void)setObjectValue:(id)fp8;

@end

