/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, SEDataSource;

@interface SEDataColumn : NSObject
{
    SEDataSource *_dataSource;
    NSString *_name;
    unsigned int _sortOrder;
    unsigned int _sortType;
    unsigned int _sortCaseSensitivity;
}

+ (id)columnForDataSource:(id)fp8 withName:(id)fp12;
- (id)initForDataSource:(id)fp8 withName:(id)fp12;
- (id)init;
- (void)dealloc;
- (id)dataSource;
- (void)setDataSource:(id)fp8;
- (id)name;
- (void)setName:(id)fp8;
- (id)rows;
- (id)cells;
- (unsigned int)sortOrder;
- (void)setSortOrder:(unsigned int)fp8;
- (unsigned int)sortType;
- (void)setSortType:(unsigned int)fp8;
- (unsigned int)sortCaseSensitivity;
- (void)setSortCaseSensitivity:(unsigned int)fp8;
- (void)insertInCells:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeFromCellsAtIndex:(unsigned int)fp8;
- (void)replaceInCells:(id)fp8 atIndex:(unsigned int)fp12;
- (void)insertInRows:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeFromRowsAtIndex:(unsigned int)fp8;
- (void)replaceInRows:(id)fp8 atIndex:(unsigned int)fp12;

@end

