/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEDocument.h"

@interface SEDocument (SEDocumentPrinting)
- (id)printInfo;
- (void)setPrintInfo:(id)fp8;
- (id)_retainedLayoutManagerForPrinting;
- (void)_printOperationDidRun:(id)fp8 success:(BOOL)fp12 contextInfo:(void *)fp16;
- (void)printShowingPrintPanel:(BOOL)fp8;
@end

