/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEDocument.h"

@interface SEDocument (SEDocumentScripting)
- (id)windows;
- (id)contents;
- (void)setContents:(id)fp8;
- (id)selection;
- (void)setSelection:(id)fp8;
- (void)setTextStorage:(id)fp8;
- (void)setDescriptionTextStorage:(id)fp8;
- (id)coerceValueForTextStorage:(id)fp8;
- (id)coerceValueForDescriptionTextStorage:(id)fp8;
- (void)_saveAsIntoFile:(id)fp8 ofType:(id)fp12;
- (id)handleCheckSyntaxScriptCommand:(id)fp8;
- (id)handleCompileScriptCommand:(id)fp8;
- (id)handleExecuteScriptCommand:(id)fp8;
- (int)_saveOptionsFromNumber:(id)fp8;
- (id)handleSaveScriptCommand:(id)fp8;
- (id)handleCloseScriptCommand:(id)fp8;
- (id)handlePrintScriptCommand:(id)fp8;
@end

