/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEDocument.h"

@interface SEDocument (SEDocumentFiling)
- (int)_lineEndingUsedInString:(id)fp8;
- (id)fileAttributesToWriteToFile:(id)fp8 ofType:(id)fp12 saveOperation:(int)fp16;
- (BOOL)writeToFile:(id)fp8 ofType:(id)fp12 originalFile:(id)fp16 saveOperation:(int)fp20;
- (BOOL)writeToFile:(id)fp8 ofType:(id)fp12;
- (void)_addResourceOfType:(unsigned long)fp8 withID:(int)fp12 usingID:(int)fp16;
- (BOOL)_writeDescriptionToURL:(id)fp8 ofType:(id)fp12;
- (BOOL)_writeWindowStateToURL:(id)fp8 ofType:(id)fp12;
- (BOOL)_writeScript:(id)fp8 toAppletAtURL:(id)fp12 withScriptData:(id)fp16;
- (BOOL)writeToURL:(id)fp8 ofType:(id)fp12;
- (BOOL)readFromFile:(id)fp8 ofType:(id)fp12;
- (void)_readAppletFromURL:(id)fp8;
- (void)_readDescriptionFromURL:(id)fp8;
- (void)_readWindowStateFromURL:(id)fp8 ofType:(id)fp12;
- (BOOL)readFromURL:(id)fp8 ofType:(id)fp12;
- (BOOL)revertToSavedFromFile:(id)fp8 ofType:(id)fp12;
- (BOOL)revertToSavedFromURL:(id)fp8 ofType:(id)fp12;
@end

