/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEEventLogItem.h"

@class NSAttributedString, NSString, SEEventLogEventItem;

@interface SEEventLogTellItem : SEEventLogItem
{
    SEEventLogEventItem *_lastEventItem;
    NSAttributedString *_endTellSource;
    NSString *_target;
}

+ (id)tellItemForSessionItem:(id)fp8 andTarget:(id)fp12;
- (id)initWithSessionItem:(id)fp8 andTarget:(id)fp12;
- (void)dealloc;
- (id)sessionItem;
- (void)setSessionItem:(id)fp8;
- (id)lastEventItem;
- (void)setLastEventItem:(id)fp8;
- (id)endTellSource;
- (void)setEndTellSource:(id)fp8;
- (id)target;
- (void)setTarget:(id)fp8;
- (id)endTellSourceForLevel:(int)fp8;
- (id)sourceOfChildrenForLevel:(int)fp8;

@end

