/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEDataItem.h"

@class NSAttributedString, NSDate;

@interface SEEventLogItem : SEDataItem
{
    NSDate *_date;
    NSAttributedString *_source;
}

- (id)initForDataSource:(id)fp8 parentItem:(id)fp12;
- (void)dealloc;
- (id)date;
- (void)setDate:(id)fp8;
- (id)source;
- (void)setSource:(id)fp8;
- (id)sourceOfChildren;
- (id)sourceForLevel:(int)fp8;
- (id)sourceOfChildrenForLevel:(int)fp8;
- (id)sessionItem;

@end

