/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEEventLogController.h"

@interface SEEventLogController (Toolbar)
- (void)setupToolbar;
- (void)findPanel:(id)fp8;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (void)toolbarWillAddItem:(id)fp8;
- (void)toolbarDidRemoveItem:(id)fp8;
- (BOOL)validateToolbarItem:(id)fp8;
@end

