/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTableView.h"

@interface SEFormattingTableView : NSTableView
{
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)awakeFromNib;
- (void)changeColor:(id)fp8;
- (void)changeFont:(id)fp8;

@end

