/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSColor, NSFont;

@interface SEFormattingInfo : NSObject
{
    NSFont *_font;
    NSColor *_color;
    struct STElement *_element;
}

+ (id)formattingInfoWithFont:(id)fp8 color:(id)fp12 andElement:(struct STElement *)fp16;
- (id)initWithFont:(id)fp8 color:(id)fp12 andElement:(struct STElement *)fp16;
- (void)dealloc;
- (id)font;
- (void)setFont:(id)fp8;
- (id)color;
- (void)setColor:(id)fp8;
- (struct STElement *)element;

@end

