/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEFormattingPreferences.h"

@interface SEFormattingPreferences (SEPrivate)
+ (void)_updateElement:(struct STElement *)fp8 withFont:(id)fp12;
+ (void)_updateElement:(struct STElement *)fp8 withColor:(id)fp12;
- (void)_addDataRowWithCategoryName:(id)fp8 andElement:(struct STElement *)fp12;
- (void)_updateTableView;
- (void)_updateButtons;
@end

