/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSImage;

@interface SEImageTextCell : NSTextFieldCell
{
    NSImage *_image;
}

- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)setImage:(id)fp8;
- (id)image;
- (BOOL)isEnabled;
- (BOOL)isSelectable;
- (BOOL)isEditable;
- (struct _NSRect)imageFrameForCellFrame:(struct _NSRect)fp8;
- (void)editWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 event:(id)fp36;
- (void)selectWithFrame:(struct _NSRect)fp8 inView:(id)fp24 editor:(id)fp28 delegate:(id)fp32 start:(int)fp36 length:(int)fp40;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (struct _NSSize)cellSize;

@end

