/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class SEScriptTextStorage;

@interface SEInsertionPoint : NSObject
{
    SEScriptTextStorage *_textStorage;
    int _index;
}

+ (id)insertionPointWithTextStorage:(id)fp8 forIndex:(int)fp12;
- (id)initWithTextStorage:(id)fp8 forIndex:(int)fp12;
- (void)dealloc;
- (id)textStorage;
- (int)index;
- (id)objectSpecifier;

@end

