/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSBox.h"

@class NSTableHeaderCell;

@interface SENavigationBar : NSBox
{
    NSTableHeaderCell *_headerCell;
}

- (void)_commonInit;
- (id)init;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)dealloc;
- (void)drawRect:(struct _NSRect)fp8;

@end

