/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@interface SEPopUpButtonCell : NSPopUpButtonCell
{
}

- (struct _NSRect)titleRectForBounds:(struct _NSRect)fp8;
- (void)drawBorderAndBackgroundWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

