/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSPopUpButton.h"

@interface SEPopUpButton : NSPopUpButton
{
}

- (void)_commonInit;
- (id)init;
- (id)initWithFrame:(struct _NSRect)fp8 pullsDown:(BOOL)fp24;
- (id)initWithCoder:(id)fp8;

@end

