/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSMutableArray, NSTableView, NSTextField, NSTextView, NSToolbarItem, SESplitView;

@interface SEResultController : NSWindowController
{
    NSTableView *_tableView;
    SESplitView *_splitView;
    NSTextView *_textView;
    NSTextField *_searchField;
    NSToolbarItem *_activeFindItem;
    NSMutableArray *_history;
}

+ (id)sharedResultController;
- (void)awakeFromNib;
- (id)init;
- (void)dealloc;
- (id)tableView;
- (id)textView;
- (id)resultWindow;
- (id)searchField;
- (id)activeFindItem;
- (id)history;
- (id)splitView;
- (void)showResultWindow:(BOOL)fp8 bringingToFront:(BOOL)fp12;
- (void)addResult:(id)fp8 fromDocument:(id)fp12 forScript:(id)fp16 withDisplayValue:(id)fp20;
- (void)clearResultForDocument:(id)fp8;
- (void)splitViewDidResizeSubviews:(id)fp8;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (BOOL)validateMenuItem:(id)fp8;
- (void)clearHistory:(id)fp8;
- (void)showResult:(id)fp8;
- (void)showScript:(id)fp8;
- (void)findResult:(id)fp8;
- (void)editingPreferencesChanged;
- (void)textViewDidChangeSelection:(id)fp8;
- (id)printInfo;
- (void)setPrintInfo:(id)fp8;
- (id)_retainedLayoutManagerForPrinting;
- (void)_printOperationDidRun:(id)fp8 success:(BOOL)fp12 contextInfo:(void *)fp16;
- (void)_pageLayoutDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)printShowingPrintPanel:(BOOL)fp8;
- (void)printDocument:(id)fp8;
- (void)runPageLayout:(id)fp8;

@end

