/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "OSAScriptController.h"

@class SEDocument;

@interface SEScriptController : OSAScriptController
{
    SEDocument *_document;
}

- (void)dealloc;
- (id)document;
- (void)setDocument:(id)fp8;
- (BOOL)compile:(id)fp8;
- (id)runScriptReturningResult:(id)fp8;
- (void)recordScript:(id)fp8;
- (void)stopScript:(id)fp8;
- (void)runScript:(id)fp8;
- (void)compileScript:(id)fp8;

@end

