/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEScriptTextStorage.h"

@interface SEScriptTextStorage (SETextStorageScripting)
- (id)valueInInsertionPointsAtIndex:(unsigned int)fp8;
- (id)insertionPoints;
- (void)setInsertionPoints:(id)fp8;
- (id)objectSpecifier;
- (id)coerceValue:(id)fp8 forKey:(id)fp12;
@end

