/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "OSAScriptView.h"

@interface SEScriptView : OSAScriptView
{
}

- (void)awakeFromNib;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)editingPreferencesChanged;
- (id)menuForEvent:(id)fp8;

@end

