/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class SEDocument;

@interface SESendProc : NSObject
{
    long _oldRefCon;
    void *_oldSendProc;
    void *_sendProc;
    SEDocument *_document;
}

- (id)initWithDocument:(id)fp8;
- (void)dealloc;

@end

