/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

struct AEDesc {
    unsigned int _field1;
    struct OpaqueAEDataStorageType **_field2;
};

struct OpaqueAEDataStorageType;

struct RGBColor {
    unsigned short red;
    unsigned short green;
    unsigned short blue;
};

struct STElement {
    short _field1;
    short _field2;
    short _field3;
    short _field4;
    unsigned char _field5;
    short _field6;
    struct RGBColor _field7;
};

struct _NSPoint {
    float _field1;
    float _field2;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSRect {
    struct _NSPoint _field1;
    struct _NSSize _field2;
};

struct _NSSize {
    float _field1;
    float _field2;
};

struct _NSZone;

typedef struct {
    int _field1;
    double _field2;
    double _field3;
    id _field4;
    char _field5;
} CDAnonymousStruct1;

