/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (SEStringFinding)
- (id)findString:(id)fp8 forView:(id)fp12 options:(unsigned int)fp16 wrap:(BOOL)fp20;
@end

