/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEAppDelegate.h"

@interface SEAppDelegate (AppleSelfTestSupport)
- (void)endTest:(CDAnonymousStruct1 *)fp8;
- (void)doTestOne:(id)fp8;
- (void)doTestTwo:(id)fp8;
- (void)doTestThree:(id)fp8;
- (void)doAllTests:(id)fp8;
- (void)application:(id)fp8 runTest:(unsigned int)fp12 duration:(double)fp16;
@end

