/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEDataRow.h"

@class NSMutableArray;

@interface SEDataItem : SEDataRow
{
    SEDataItem *_parentItem;
    NSMutableArray *_items;
}

+ (id)itemForDataSource:(id)fp8 parentItem:(id)fp12;
- (id)initForDataSource:(id)fp8 parentItem:(id)fp12;
- (id)init;
- (void)dealloc;
- (id)parentItem;
- (void)setParentItem:(id)fp8;
- (id)items;
- (BOOL)hasParentItem;
- (BOOL)hasItems;
- (id)itemAtIndex:(unsigned int)fp8;
- (void)addInItems:(id)fp8;
- (void)insertInItems:(id)fp8 atIndex:(unsigned int)fp12;
- (void)removeItem:(id)fp8;
- (void)removeFromItemsAtIndex:(unsigned int)fp8;
- (void)removeAllItems;
- (void)replaceInItems:(id)fp8 atIndex:(unsigned int)fp12;

@end

