/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class NSButton, NSDictionary, NSPopUpButton, NSSegmentedControl, NSTabView, NSTextField, NSTextView, NSToolbarItem, NSView, NSWindow, OSAScript, OSAScriptParser, SEBundleContentsController, SEEventLogSessionItem, SENavigationBar, SEPopUpButton, SEScriptController, SEScriptTextStorage, SEScriptView, SESplitView, SETextStorage;

@interface SEDocument : NSDocument
{
    SEScriptTextStorage *_textStorage;
    SETextStorage *_descriptionTextStorage;
    OSAScript *_script;
    BOOL _shouldCancelExecution;
    int _scriptState;
    BOOL _runOnly;
    BOOL _stayOpen;
    BOOL _showStartupScreen;
    BOOL _requiresClassic;
    int _lineEndings;
    OSAScriptParser *_parser;
    float _minSplitPosition;
    NSDictionary *_savedWindowState;
    SEScriptController *_controller;
    NSWindow *_scriptWindow;
    SEScriptView *_scriptView;
    NSTextField *_findField;
    NSPopUpButton *_elementsPopUpButton;
    SESplitView *_splitView;
    NSTabView *_tabView;
    NSTextView *_resultTextView;
    NSTextView *_eventLogTextView;
    NSToolbarItem *_activeFindItem;
    NSTextView *_descriptionTextView;
    SEPopUpButton *_languagePopUpButton;
    SENavigationBar *_navigationBar;
    NSSegmentedControl *_tabViewControl;
    SEBundleContentsController *_bundleContentsController;
    NSView *_accessoryView;
    NSPopUpButton *_fileFormatPopUpButton;
    NSPopUpButton *_lineEndingsPopUpButton;
    NSButton *_runOnlyButton;
    NSButton *_stayOpenButton;
    NSButton *_showStartupScreenButton;
    NSButton *_requiresClassicButton;
    SEEventLogSessionItem *_eventLogSessionItem;
}

- (id)init;
- (void)dealloc;
- (void)canCloseDocumentWithDelegate:(id)fp8 shouldCloseSelector:(SEL)fp12 contextInfo:(void *)fp16;
- (id)textStorage;
- (id)descriptionTextStorage;
- (id)language;
- (void)setLanguage:(id)fp8;
- (id)script;
- (void)setScript:(id)fp8;
- (BOOL)isCompiling;
- (void)setIsCompiling:(BOOL)fp8;
- (BOOL)shouldCancelExecution;
- (void)setShouldCancelExecution:(BOOL)fp8;
- (id)eventLogSessionItem;
- (void)setEventLogSessionItem:(id)fp8;
- (int)scriptState;
- (void)setScriptState:(int)fp8;
- (BOOL)runOnly;
- (void)setRunOnly:(BOOL)fp8;
- (BOOL)stayOpen;
- (void)setStayOpen:(BOOL)fp8;
- (BOOL)showStartupScreen;
- (void)setShowStartupScreen:(BOOL)fp8;
- (BOOL)requiresClassic;
- (void)setRequiresClassic:(BOOL)fp8;
- (int)lineEndings;
- (void)setLineEndings:(int)fp8;
- (id)parser;
- (void)setParser:(id)fp8;
- (id)controller;
- (void)setController:(id)fp8;
- (void)setUndoManager:(id)fp8;
- (id)scriptWindow;
- (id)scriptView;
- (id)findField;
- (id)elementsPopUpButton;
- (id)activeFindItem;
- (id)languagePopUpButton;
- (id)splitView;
- (id)tabView;
- (id)resultTextView;
- (id)eventLogTextView;
- (id)descriptionTextView;
- (id)navigationBar;
- (id)tabViewControl;
- (id)bundleContentsController;
- (BOOL)eventLogTextViewIsVisible;
- (id)windowNibName;
- (void)windowControllerDidLoadNib:(id)fp8;
- (id)source;
- (id)scriptFromSource;
- (BOOL)compileScript:(id)fp8 withUndo:(BOOL)fp12;
- (void)languageChanged;
- (void)sourceStylesChanged;
- (void)editingPreferencesChanged;
- (void)navigationBarToggled;
- (void)showNavigationBar:(BOOL)fp8;
- (id)windowState;
- (void)setWindowState:(id)fp8;
- (void)addElementsOfElement:(id)fp8 forLevel:(int)fp12;
- (void)updateElementsList:(id)fp8;
- (id)findElementWithRange:(struct _NSRange)fp8 inElement:(id)fp16;
- (void)updateElementsListSelection:(id)fp8;
- (void)willPopUp:(id)fp8;
- (BOOL)textView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (void)splitViewDidResizeSubviews:(id)fp8;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (void)textViewDidChangeSelection:(id)fp8;

@end

