/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEDocument.h"

@interface SEDocument (Actions)
- (BOOL)validateMenuItem:(id)fp8;
- (void)recordScript:(id)fp8;
- (void)stopScript:(id)fp8;
- (void)runScript:(id)fp8;
- (void)compileScript:(id)fp8;
- (void)selectElement:(id)fp8;
- (void)changeLanguage:(id)fp8;
- (void)showResult:(id)fp8;
- (void)showEventLog:(id)fp8;
- (void)showDescription:(id)fp8;
- (void)showDebug:(id)fp8;
- (void)showResultHistory:(id)fp8;
- (void)showEventLogHistory:(id)fp8;
- (void)pasteReference:(id)fp8;
- (void)changeView:(id)fp8;
- (void)toggleBundleContents:(id)fp8;
- (void)debug:(id)fp8;
- (void)pauseDebug:(id)fp8;
- (void)continueDebug:(id)fp8;
- (void)restartDebug:(id)fp8;
- (void)stepIntoDebug:(id)fp8;
- (void)stepOutDebug:(id)fp8;
- (void)stepOverDebug:(id)fp8;
@end

