/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEPreferences.h"

@class NSButton, NSTextField;

@interface SEEditingPreferences : SEPreferences
{
    int _lineEndings;
    int _fileEncoding;
    BOOL _wrapsLines;
    BOOL _indentsWrappedLines;
    int _indentWidth;
    BOOL _editorUsesTabs;
    int _tabWidth;
    BOOL _usesScriptAssistant;
    NSButton *_editorUsesTabsButton;
    NSButton *_indentsWrappedLinesButton;
    NSTextField *_indentWidthTextField;
    NSTextField *_tabWidthTextField;
    NSButton *_wrapsLinesButton;
    NSButton *_usesScriptAssistantButton;
}

+ (id)sharedEditingPreferences;
- (id)initWithOwner:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (void)notify;
- (int)lineEndings;
- (void)setLineEndings:(int)fp8;
- (int)fileEncoding;
- (void)setFileEncoding:(int)fp8;
- (BOOL)wrapsLines;
- (void)setWrapsLines:(BOOL)fp8;
- (BOOL)indentsWrappedLines;
- (void)setIndentsWrappedLines:(BOOL)fp8;
- (int)indentWidth;
- (void)setIndentWidth:(int)fp8;
- (BOOL)editorUsesTabs;
- (void)setEditorUsesTabs:(BOOL)fp8;
- (int)tabWidth;
- (void)setTabWidth:(int)fp8;
- (BOOL)usesScriptAssistant;
- (void)setUsesScriptAssistant:(BOOL)fp8;
- (void)read;
- (void)write;
- (void)editorUsesTabsChanged:(id)fp8;
- (void)fileEncodingChanged:(id)fp8;
- (void)indentWidthChanged:(id)fp8;
- (void)indentsWrappedLinesChanged:(id)fp8;
- (void)lineEndingsChanged:(id)fp8;
- (void)tabWidthChanged:(id)fp8;
- (void)wrapsLinesChanged:(id)fp8;
- (void)usesScriptAssistantChanged:(id)fp8;

@end

