/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSOutlineView, NSPopUpButton, NSTextField, NSTextView, NSToolbarItem, SEDataSource, SESplitView;

@interface SEEventLogController : NSWindowController
{
    NSOutlineView *_outlineView;
    SEDataSource *_historyDataSource;
    NSTextView *_textView;
    SESplitView *_splitView;
    NSTextField *_searchField;
    NSPopUpButton *_optionsPopUpButton;
    NSToolbarItem *_activeFindItem;
    int _options;
}

+ (id)sharedEventLogController;
- (void)awakeFromNib;
- (id)init;
- (void)dealloc;
- (id)outlineView;
- (id)splitView;
- (id)historyDataSource;
- (id)textView;
- (id)eventLogWindow;
- (id)searchField;
- (id)activeFindItem;
- (id)optionsPopUpButton;
- (int)options;
- (void)setOptions:(int)fp8;
- (int)_getCategoryForEvent:(struct AEDesc *)fp8;
- (void)_logEndTellForSessionItem:(id)fp8;
- (void)_logTell:(struct AEDesc *)fp8 forSessionItem:(id)fp12;
- (void)showEventLogWindow:(BOOL)fp8 bringingToFront:(BOOL)fp12;
- (BOOL)_shouldLogEventsForDocument:(id)fp8;
- (void)beginLogForDocument:(id)fp8;
- (void)endLogForDocument:(id)fp8 error:(id)fp12;
- (void)logEvent:(struct AEDesc *)fp8 forDocument:(id)fp12;
- (void)logResult:(struct AEDesc *)fp8 forDocument:(id)fp12;
- (void)splitViewDidResizeSubviews:(id)fp8;
- (float)splitView:(id)fp8 constrainMaxCoordinate:(float)fp12 ofSubviewAt:(int)fp16;
- (void)splitView:(id)fp8 resizeSubviewsWithOldSize:(struct _NSSize)fp12;
- (BOOL)validateMenuItem:(id)fp8;
- (void)clearHistory:(id)fp8;
- (void)showEventLog:(id)fp8;
- (void)showScript:(id)fp8;
- (void)findEventLog:(id)fp8;
- (void)changeEventLogOptions:(id)fp8;
- (void)editingPreferencesChanged;
- (void)textViewDidChangeSelection:(id)fp8;
- (id)printInfo;
- (void)setPrintInfo:(id)fp8;
- (id)_retainedLayoutManagerForPrinting;
- (void)_printOperationDidRun:(id)fp8 success:(BOOL)fp12 contextInfo:(void *)fp16;
- (void)_pageLayoutDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)printShowingPrintPanel:(BOOL)fp8;
- (void)printDocument:(id)fp8;
- (void)runPageLayout:(id)fp8;

@end

