/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEEventLogItem.h"

@class NSDate, NSString, SEDocument, SEEventLogTellItem;

@interface SEEventLogSessionItem : SEEventLogItem
{
    SEDocument *_document;
    int _executionCount;
    SEEventLogTellItem *_lastTellItem;
    NSString *_scriptSource;
    NSDate *_sourceDate;
    BOOL _logToDocument;
}

+ (id)sessionItemForDocument:(id)fp8 andDataSource:(id)fp12;
- (id)initForDocument:(id)fp8 andDataSource:(id)fp12;
- (void)dealloc;
- (id)document;
- (void)setDocument:(id)fp8;
- (id)scriptSource;
- (id)source;
- (void)setSource:(id)fp8;
- (int)executionCount;
- (void)setExecutionCount:(int)fp8;
- (id)lastTellItem;
- (void)setLastTellItem:(id)fp8;
- (id)sourceDate;
- (void)setSourceDate:(id)fp8;
- (BOOL)logToDocument;
- (void)setLogToDocument:(BOOL)fp8;

@end

