/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEEventLogController.h"

@interface SEEventLogController (Outline)
- (void)setupOutlineView;
- (void)_selectionChanged;
- (void)outlineViewSelectionDidChange:(id)fp8;
- (void)outlineViewSelectionIsChanging:(id)fp8;
@end

