/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEEventLogItem.h"

@interface SEEventLogResultItem : SEEventLogItem
{
}

+ (id)resultItemForEventItem:(id)fp8;
- (id)initWithEventItem:(id)fp8;
- (id)eventItem;
- (void)setEventItem:(id)fp8;

@end

