/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEPreferences.h"

@class NSButton, SEDataSource, SEFormattingTableView;

@interface SEFormattingPreferences : SEPreferences
{
    SEFormattingTableView *_tableView;
    SEDataSource *_dataSource;
    NSButton *_applyButton;
    NSButton *_revertButton;
    NSButton *_useDefaultsButton;
    struct STElement **_sourceStyles;
    struct STElement **_currentSourceStyles;
    BOOL _changed;
    BOOL _selectionChanging;
}

+ (id)sharedFormattingPreferences;
+ (id)defaultFont;
+ (void)invalidateDefaultFont;
- (float)_largestFontSize;
- (void)_updateTableCellHeights;
- (id)initWithOwner:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (id)tableView;
- (id)dataSource;
- (struct STElement **)sourceStyles;
- (void)setSourceStyles:(struct STElement **)fp8;
- (struct STElement **)currentSourceStyles;
- (void)setCurrentSourceStyles:(struct STElement **)fp8;
- (BOOL)changed;
- (void)setChanged:(BOOL)fp8;
- (void)apply:(id)fp8;
- (void)revert:(id)fp8;
- (void)useDefaults:(id)fp8;
- (void)showColors:(id)fp8;
- (void)showFonts:(id)fp8;
- (void)showPanel:(id)fp8;
- (void)read;
- (void)write;
- (void)changeColor:(id)fp8;
- (void)changeFont:(id)fp8;
- (void)tableViewSelectionDidChange:(id)fp8;
- (void)tableViewSelectionIsChanging:(id)fp8;

@end

