/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEPreferences.h"

@class NSButton, NSMatrix, NSTextField;

@interface SEHistoryPreferences : SEPreferences
{
    BOOL _enableEventLogHistory;
    BOOL _unlimitedEventLogEntries;
    int _numberOfEventLogEntries;
    BOOL _enableResultHistory;
    BOOL _unlimitedResultEntries;
    int _numberOfResultEntries;
    BOOL _logOnlyWhenWindowIsVisible;
    NSButton *_enableEventLogHistoryButton;
    NSButton *_enableResultHistoryButton;
    NSTextField *_eventLogHistoryEntriesTextField;
    NSMatrix *_eventLogHistoryMatrix;
    NSButton *_logOnlyWhenWIndowIsVisibleButton;
    NSTextField *_resultHistoryEntriesTextField;
    NSMatrix *_resultHistoryMatrix;
}

+ (id)sharedHistoryPreferences;
- (id)initWithOwner:(id)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (BOOL)enableEventLogHistory;
- (void)setEnableEventLogHistory:(BOOL)fp8;
- (BOOL)unlimitedEventLogEntries;
- (void)setUnlimitedEventLogEntries:(BOOL)fp8;
- (int)numberOfEventLogEntries;
- (void)setNumberOfEventLogEntries:(int)fp8;
- (BOOL)enableResultHistory;
- (void)setEnableResultHistory:(BOOL)fp8;
- (BOOL)unlimitedResultEntries;
- (void)setUnlimitedResultEntries:(BOOL)fp8;
- (int)numberOfResultEntries;
- (void)setNumberOfResultEntries:(int)fp8;
- (BOOL)logOnlyWhenWindowIsVisible;
- (void)setLogOnlyWhenWindowIsVisible:(BOOL)fp8;
- (void)read;
- (void)write;
- (void)enableEventLogHistoryChanged:(id)fp8;
- (void)enableResultHistoryChanged:(id)fp8;
- (void)logOnlyWhenWindowIsVisibleChanged:(id)fp8;
- (void)numberOfEventLogEntriesChanged:(id)fp8;
- (void)numberOfResultEntriesChanged:(id)fp8;
- (void)unlimitedEventLogEntriesChanged:(id)fp8;
- (void)unlimitedResultEntriesChanged:(id)fp8;

@end

