/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSImage, NSString, NSView, SEPreferencesController;

@interface SEPreferences : NSObject
{
    NSView *_view;
    SEPreferencesController *_owner;
    NSString *_label;
    NSString *_identifier;
    NSImage *_image;
}

- (id)initWithOwner:(id)fp8;
- (void)dealloc;
- (id)owner;
- (void)setOwner:(id)fp8;
- (id)view;
- (void)setView:(id)fp8;
- (id)label;
- (void)setLabel:(id)fp8;
- (id)identifier;
- (void)setIdentifier:(id)fp8;
- (id)image;
- (void)setImage:(id)fp8;
- (void)read;
- (void)write;

@end

