/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSMutableArray, NSMutableDictionary, NSView, NSWindow;

@interface SEPreferencesController : NSObject
{
    NSWindow *_preferencesWindow;
    NSView *_transitionView;
    NSButton *_transitionButton;
    NSMutableDictionary *_preferences;
    NSMutableArray *_orderedPreferences;
}

+ (id)sharedPreferencesController;
- (id)init;
- (void)dealloc;
- (id)preferencesWindow;
- (id)transitionView;
- (id)transitionButton;
- (id)preferences;
- (id)orderedPreferences;
- (void)readPreferences;
- (void)writePreferences;
- (void)showPreferencesWindow:(BOOL)fp8 bringingToFront:(BOOL)fp12;
- (void)addPreferences:(id)fp8;
- (void)findAndLoadPreferences;
- (id)preferencesWithIdentifier:(id)fp8;
- (void)choosePreferencesWithIdentifier:(id)fp8;
- (void)choosePreferences:(id)fp8;

@end

