/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "SEResultController.h"

@interface SEResultController (Table)
- (void)setupTableView;
- (int)numberOfRowsInTableView:(id)fp8;
- (id)tableView:(id)fp8 objectValueForTableColumn:(id)fp12 row:(int)fp16;
- (void)_selectionChanged:(id)fp8;
- (void)tableViewSelectionDidChange:(id)fp8;
- (void)tableViewSelectionIsChanging:(id)fp8;
@end

