/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSTextView;

@interface SETextSelection : NSObject
{
    NSTextView *_textView;
    id _subtextStorage;
}

+ (id)selectionForTextView:(id)fp8;
- (id)initForTextView:(id)fp8;
- (void)dealloc;
- (id)textView;
- (id)contents;
- (void)setContents:(id)fp8;
- (id)characterRange;
- (id)objectSpecifier;

@end

