/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSMatrix, NSPopUpButton, NSString, NSTextField;

@interface SETextFinder : NSObject
{
    NSString *_findString;
    NSTextField *_findTextField;
    NSTextField *_replaceTextField;
    NSButton *_ignoreCaseButton;
    NSButton *_findNextButton;
    NSMatrix *_replaceAllScopeMatrix;
    NSTextField *_statusField;
    NSPopUpButton *_findMethodPopUpButton;
    BOOL _lastFindWasSuccessful;
}

+ (id)sharedTextFinder;
- (id)init;
- (void)dealloc;
- (void)appDidActivate:(id)fp8;
- (void)loadFindStringFromPasteboard;
- (void)loadFindStringToPasteboard;
- (void)loadUI;
- (id)findString;
- (void)setFindString:(id)fp8;
- (void)setFindString:(id)fp8 writeToPasteboard:(BOOL)fp12;
- (id)findTextField;
- (id)replaceTextField;
- (id)ignoreCaseButton;
- (id)findNextButton;
- (id)replaceAllScopeMatrix;
- (id)statusField;
- (id)findMethodPopUpButton;
- (id)textObjectToSearchIn;
- (BOOL)lastFindWasSuccessful;
- (void)setLastFindWasSuccessful:(BOOL)fp8;
- (id)findPanel;
- (BOOL)find:(BOOL)fp8;
- (void)orderFrontFindPanel:(id)fp8;
- (void)findNextAndOrderFindPanelOut:(id)fp8;
- (void)findNext:(id)fp8;
- (void)findPrevious:(id)fp8;
- (void)replace:(id)fp8;
- (void)replaceAndFind:(id)fp8;
- (void)replaceAll:(id)fp8;
- (void)takeFindStringFromSelection:(id)fp8;
- (void)jumpToSelection:(id)fp8;

@end

